// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/dispatcher.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ToolState int32

const (
	ToolState_UNSPECIFIED ToolState = 0
	ToolState_PENDING     ToolState = 1
	ToolState_RUNNING     ToolState = 2
	ToolState_SUCCEEDED   ToolState = 3
	ToolState_FAILED      ToolState = 4
	ToolState_CANCELLED   ToolState = 5
)

// Enum value maps for ToolState.
var (
	ToolState_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "PENDING",
		2: "RUNNING",
		3: "SUCCEEDED",
		4: "FAILED",
		5: "CANCELLED",
	}
	ToolState_value = map[string]int32{
		"UNSPECIFIED": 0,
		"PENDING":     1,
		"RUNNING":     2,
		"SUCCEEDED":   3,
		"FAILED":      4,
		"CANCELLED":   5,
	}
)

func (x ToolState) Enum() *ToolState {
	p := new(ToolState)
	*p = x
	return p
}

func (x ToolState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToolState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dispatcher_proto_enumTypes[0].Descriptor()
}

func (ToolState) Type() protoreflect.EnumType {
	return &file_proto_dispatcher_proto_enumTypes[0]
}

func (x ToolState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToolState.Descriptor instead.
func (ToolState) EnumDescriptor() ([]byte, []int) {
	return file_proto_dispatcher_proto_rawDescGZIP(), []int{0}
}

type LaunchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolName      string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchRequest) Reset() {
	*x = LaunchRequest{}
	mi := &file_proto_dispatcher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchRequest) ProtoMessage() {}

func (x *LaunchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatcher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchRequest.ProtoReflect.Descriptor instead.
func (*LaunchRequest) Descriptor() ([]byte, []int) {
	return file_proto_dispatcher_proto_rawDescGZIP(), []int{0}
}

func (x *LaunchRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *LaunchRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type LaunchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolId        *ToolId                `protobuf:"bytes,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchResponse) Reset() {
	*x = LaunchResponse{}
	mi := &file_proto_dispatcher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchResponse) ProtoMessage() {}

func (x *LaunchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatcher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchResponse.ProtoReflect.Descriptor instead.
func (*LaunchResponse) Descriptor() ([]byte, []int) {
	return file_proto_dispatcher_proto_rawDescGZIP(), []int{1}
}

func (x *LaunchResponse) GetToolId() *ToolId {
	if x != nil {
		return x.ToolId
	}
	return nil
}

type ToolId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolId) Reset() {
	*x = ToolId{}
	mi := &file_proto_dispatcher_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolId) ProtoMessage() {}

func (x *ToolId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatcher_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolId.ProtoReflect.Descriptor instead.
func (*ToolId) Descriptor() ([]byte, []int) {
	return file_proto_dispatcher_proto_rawDescGZIP(), []int{2}
}

func (x *ToolId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ToolStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolId        *ToolId                `protobuf:"bytes,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	State         ToolState              `protobuf:"varint,2,opt,name=state,proto3,enum=dispatcher.ToolState" json:"state,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // error message, progress info, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolStatus) Reset() {
	*x = ToolStatus{}
	mi := &file_proto_dispatcher_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolStatus) ProtoMessage() {}

func (x *ToolStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatcher_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolStatus.ProtoReflect.Descriptor instead.
func (*ToolStatus) Descriptor() ([]byte, []int) {
	return file_proto_dispatcher_proto_rawDescGZIP(), []int{3}
}

func (x *ToolStatus) GetToolId() *ToolId {
	if x != nil {
		return x.ToolId
	}
	return nil
}

func (x *ToolStatus) GetState() ToolState {
	if x != nil {
		return x.State
	}
	return ToolState_UNSPECIFIED
}

func (x *ToolStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_dispatcher_proto protoreflect.FileDescriptor

const file_proto_dispatcher_proto_rawDesc = "" +
	"\n" +
	"\x16proto/dispatcher.proto\x12\n" +
	"dispatcher\"\xb6\x01\n" +
	"\rLaunchRequest\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12I\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2).dispatcher.LaunchRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\x0eLaunchResponse\x12+\n" +
	"\atool_id\x18\x01 \x01(\v2\x12.dispatcher.ToolIdR\x06toolId\"\x18\n" +
	"\x06ToolId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x80\x01\n" +
	"\n" +
	"ToolStatus\x12+\n" +
	"\atool_id\x18\x01 \x01(\v2\x12.dispatcher.ToolIdR\x06toolId\x12+\n" +
	"\x05state\x18\x02 \x01(\x0e2\x15.dispatcher.ToolStateR\x05state\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*`\n" +
	"\tToolState\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\r\n" +
	"\tSUCCEEDED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\x12\r\n" +
	"\tCANCELLED\x10\x052\x90\x01\n" +
	"\n" +
	"Dispatcher\x12C\n" +
	"\n" +
	"LaunchTool\x12\x19.dispatcher.LaunchRequest\x1a\x1a.dispatcher.LaunchResponse\x12=\n" +
	"\x0fCheckToolStatus\x12\x12.dispatcher.ToolId\x1a\x16.dispatcher.ToolStatusB$Z\"github.com/unkcpz/dispatcher/protob\x06proto3"

var (
	file_proto_dispatcher_proto_rawDescOnce sync.Once
	file_proto_dispatcher_proto_rawDescData []byte
)

func file_proto_dispatcher_proto_rawDescGZIP() []byte {
	file_proto_dispatcher_proto_rawDescOnce.Do(func() {
		file_proto_dispatcher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dispatcher_proto_rawDesc), len(file_proto_dispatcher_proto_rawDesc)))
	})
	return file_proto_dispatcher_proto_rawDescData
}

var file_proto_dispatcher_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_dispatcher_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_dispatcher_proto_goTypes = []any{
	(ToolState)(0),         // 0: dispatcher.ToolState
	(*LaunchRequest)(nil),  // 1: dispatcher.LaunchRequest
	(*LaunchResponse)(nil), // 2: dispatcher.LaunchResponse
	(*ToolId)(nil),         // 3: dispatcher.ToolId
	(*ToolStatus)(nil),     // 4: dispatcher.ToolStatus
	nil,                    // 5: dispatcher.LaunchRequest.ParametersEntry
}
var file_proto_dispatcher_proto_depIdxs = []int32{
	5, // 0: dispatcher.LaunchRequest.parameters:type_name -> dispatcher.LaunchRequest.ParametersEntry
	3, // 1: dispatcher.LaunchResponse.tool_id:type_name -> dispatcher.ToolId
	3, // 2: dispatcher.ToolStatus.tool_id:type_name -> dispatcher.ToolId
	0, // 3: dispatcher.ToolStatus.state:type_name -> dispatcher.ToolState
	1, // 4: dispatcher.Dispatcher.LaunchTool:input_type -> dispatcher.LaunchRequest
	3, // 5: dispatcher.Dispatcher.CheckToolStatus:input_type -> dispatcher.ToolId
	2, // 6: dispatcher.Dispatcher.LaunchTool:output_type -> dispatcher.LaunchResponse
	4, // 7: dispatcher.Dispatcher.CheckToolStatus:output_type -> dispatcher.ToolStatus
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_dispatcher_proto_init() }
func file_proto_dispatcher_proto_init() {
	if File_proto_dispatcher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dispatcher_proto_rawDesc), len(file_proto_dispatcher_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dispatcher_proto_goTypes,
		DependencyIndexes: file_proto_dispatcher_proto_depIdxs,
		EnumInfos:         file_proto_dispatcher_proto_enumTypes,
		MessageInfos:      file_proto_dispatcher_proto_msgTypes,
	}.Build()
	File_proto_dispatcher_proto = out.File
	file_proto_dispatcher_proto_goTypes = nil
	file_proto_dispatcher_proto_depIdxs = nil
}
